image: node:16

stages:
  - test

test:
  stage: test
  artifacts:
    paths:
      - coverage/
  script:
    # Build
    - npm install
    - npx hardhat compile
    - npx hardhat typechain
    # Test
    - npx hardhat coverage
    # Deploy
    - npx hardhat run scripts/deploy-system.ts
    - npx hardhat run scripts/deploy-chain.ts
    # Lint
    - npm run solhint
    - npm run eslint
    - npm run prettier

pages:
  stage: test
  needs:
    - test
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  only:
    - main
